name: CI

on:
  push:
  workflow_call:

jobs:
  deno:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Build Reason
        run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"
      
      - name: Build Version
        run: |
          dotnet tool install --global minver-cli --version 5.0.0
          version=$(minver --tag-prefix v)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "### Version: $version" >> $GITHUB_STEP_SUMMARY
          echo $(jq --arg version "$version" '.version = $version' deno.json) > deno.json
          cat deno.json
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Code Style
        run: deno fmt --check

      - name: Linting
        run: deno lint

      - name: Type Check
        run: deno check scripts/*.ts *.ts src/*.ts

      - name: Tests
        run: |
          deno test --coverage=cov/
          deno coverage cov/

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno task build
